/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiInsights: typeof import('./src/components/dashboard/AiInsights.vue')['default']
    ApiFailureChart: typeof import('./src/components/dashboard/ApiFailureChart.vue')['default']
    ApiSuccessFailureChart: typeof import('./src/components/dashboard/ApiSuccessFailureChart.vue')['default']
    AuditLogExplorer: typeof import('./src/components/dashboard/AuditLogExplorer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    JourneyExplorer: typeof import('./src/components/dashboard/JourneyExplorer.vue')['default']
    JourneyTimeline: typeof import('./src/components/journey/JourneyTimeline.vue')['default']
    KpiCard: typeof import('./src/components/dashboard/KpiCard.vue')['default']
    OverallApiFailureList: typeof import('./src/components/dashboard/OverallApiFailureList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopErrorTypesChart: typeof import('./src/components/dashboard/TopErrorTypesChart.vue')['default']
    UserAverageTimeChart: typeof import('./src/components/dashboard/UserAverageTimeChart.vue')['default']
    UserJourneyFunnelChart: typeof import('./src/components/dashboard/UserJourneyFunnelChart.vue')['default']
  }
}
